### ISSUE TITLE
Is this in-memory only?

### ISSUE THREAD

**Issue by joshcho** [mhuebert/re-db#17]
I am looking around the docs, and I notice that some examples load this for in-memory. Is there persistence, like in Datalevin? If not, what would be some ways to achieve persistence with re-db?

**Comment by mhuebert** [comment]
Hi @joshcho, re-db started as in-memory only but has since been extended to support some persisted use-cases. `re-db.triplestore` has a protocol for accessing triplestores which is used to implement [integrations](https://github.com/mhuebert/re-db/tree/main/src/main/re_db/integrations) (in-memory, datalevin, and atomic currently). The `re-db.read` namespace can then read from any of these databases reactively using some bookkeeping and pattern-matching on datoms in the tx-log (nothing too sophisticated at this time but often sufficient). In `re-db.sync` there are some utilities for sending this stuff across the wire (eg. to a `re-db.in-memory` instance in a browser), and `re-db.reactive` defines some reactive primitives similar to what reagent provides but consistent across jvm/js.

**Comment by joshcho** [comment]
Great! Anything I should keep in mind when I try to use re-db as a replacement for datalevin?

**Comment by mhuebert** [comment]
@joshcho as there is no persistence, I am using this father in combination with Datalevin (eg I use the read, reactive + sync namespaces on the server to read from Datalevin and then send changes to the client, where data sits in an re-db.in-memory instance and can be reactively subscribed to from react)

**Comment by joshcho** [comment]
Oh, I see. I did not read it carefully enough. I will give it a go.
